namespace Domain.Entities.VideoEntities;

/// <summary>
/// Represents a live streaming session (Zoom/YouTube) for a course
/// </summary>
public class LiveSession : BaseEntity<Guid>
{
    /// <summary>
    /// Live session title
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Live session description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Meeting link — kept nullable for backward-compatibility with old records.
    /// New sessions use JaaS and leave this blank.
    /// </summary>
    public string? MeetingLink { get; set; }

    /// <summary>
    /// JaaS / Jitsi room name generated by the backend.
    /// Format: course-{courseId}-session-{sessionId}
    /// </summary>
    public string? RoomName { get; set; }

    /// <summary>
    /// Meeting provider identifier. "JITSI" for JaaS sessions.
    /// </summary>
    public string Provider { get; set; } = "JITSI";

    /// <summary>
    /// Instructor/creator of this session (FK to AspNetUsers)
    /// </summary>
    public string InstructorId { get; set; } = string.Empty;

    /// <summary>
    /// YouTube Live Video ID (for live stream) - Optional, for backward compatibility
    /// </summary>
    public string? YouTubeLiveVideoId { get; set; }

    /// <summary>
    /// YouTube Video ID of the recorded session (available after live ends)
    /// Nullable - only set when recording is available
    /// </summary>
    public string? RecordingVideoId { get; set; }

    /// <summary>
    /// Foreign key to Course
    /// </summary>
    public Guid CourseId { get; set; }

    /// <summary>
    /// When the live session is scheduled to start
    /// </summary>
    public DateTime ScheduledStart { get; set; }

    /// <summary>
    /// When the live session is scheduled to end
    /// </summary>
    public DateTime ScheduledEnd { get; set; }

    /// <summary>
    /// Whether the live session is currently active
    /// Admin can manually activate/deactivate
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Whether the recorded version is available after live ends
    /// </summary>
    public bool IsRecordedAvailable { get; set; }

    /// <summary>
    /// Timestamp when created
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Timestamp when last updated
    /// </summary>
    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Navigation property to Course
    /// </summary>
    public CourseEntities.Course Course { get; set; } = null!;

    /// <summary>
    /// Navigation property to access logs
    /// </summary>
    public ICollection<VideoAccessLog> AccessLogs { get; set; } = new List<VideoAccessLog>();
}
